#include <catch2/catch_test_macros.hpp>
#include <parcae/dsl/dsl_emit_cpu.hpp>
#include <parcae/dsl/dsl_emit_cuda.hpp>
#include <parcae/dsl/param_ir.hpp>
#include <parcae/dsl/primitive_ir.hpp>
#include <parcae/dsl/theory_ir.hpp>
#include <parcae/dsl/z29_expr.hpp>
#include <string>

TEST_CASE("DslEmitCuda emit_expr uses Z29Device", "[dsl][emit][cuda]") {
    const Z29Expr::Ptr expr = Z29Expr::add(Z29Expr::var("x"), Z29Expr::var("shift"));
    const StatusOr<std::string> cpp = DslEmitCuda::emit_expr(expr, "x", "in[i]");
    REQUIRE(cpp.ok());
    REQUIRE(cpp.value() == "Z29Device::add(in[i], shift)");
}

TEST_CASE("DslEmitCuda emit_theory_header Kernel façade", "[dsl][emit][cuda]") {
    const StatusOr<ParamIr> shift = ParamIr::make("shift", 0, 28);
    REQUIRE(shift.ok());
    const Z29Expr::Ptr x = Z29Expr::var("x");
    const Z29Expr::Ptr s = Z29Expr::var("shift");
    const StatusOr<TheoryIr> theory =
        TheoryIr::make("dsl_caesar", TheoryIr::Family::Elementwise, TheoryIr::Tier::A,
                       TheoryIr::InterruptMode::ElementwiseDefault, {shift.value()},
                       Z29Expr::add(x, s), Z29Expr::sub(x, s));
    REQUIRE(theory.ok());

    const StatusOr<std::string> header = DslEmitCuda::emit_theory_header(theory.value());
    REQUIRE(header.ok());
    const std::string& text = header.value();
    REQUIRE(text.find("Generated by parcae-compile (DslEmitCuda)") != std::string::npos);
    REQUIRE(text.find("class DslCaesarKernel") != std::string::npos);
    REQUIRE(text.find("launch_device(") != std::string::npos);
    REQUIRE(text.find("apply_host(") != std::string::npos);
    REQUIRE(text.find("#include \"../params.hpp\"") != std::string::npos);
    REQUIRE(text.find("CudaDir direction") != std::string::npos);
    REQUIRE(text.find("DslCaesarKernel() = delete") != std::string::npos);
}

TEST_CASE("DslEmitCuda emit_theory_cu has Z29Device kernel", "[dsl][emit][cuda]") {
    const StatusOr<ParamIr> shift = ParamIr::make("shift", 0, 28);
    REQUIRE(shift.ok());
    const Z29Expr::Ptr x = Z29Expr::var("x");
    const Z29Expr::Ptr s = Z29Expr::var("shift");
    const StatusOr<TheoryIr> theory =
        TheoryIr::make("dsl_caesar", TheoryIr::Family::Elementwise, TheoryIr::Tier::A,
                       TheoryIr::InterruptMode::ElementwiseDefault, {shift.value()},
                       Z29Expr::add(x, s), Z29Expr::sub(x, s));
    REQUIRE(theory.ok());

    const StatusOr<std::string> cu = DslEmitCuda::emit_theory_cu(theory.value());
    REQUIRE(cu.ok());
    const std::string& text = cu.value();
    REQUIRE(text.find("#include \"DslCaesarKernel.hpp\"") != std::string::npos);
    REQUIRE(text.find("#include \"../z29_device.hpp\"") != std::string::npos);
    REQUIRE(text.find("__global__ void dsl_caesar_kernel(") != std::string::npos);
    REQUIRE(text.find("kThreadsPerBlock = 256") != std::string::npos);
    REQUIRE(text.find("Z29Device::add(in[i], shift)") != std::string::npos);
    REQUIRE(text.find("Z29Device::sub(in[i], shift)") != std::string::npos);
    REQUIRE(text.find("DslCaesarKernel::launch_device(") != std::string::npos);
    REQUIRE(text.find("DslCaesarKernel::apply_host(") != std::string::npos);
    REQUIRE(text.find("DeviceBuffer") != std::string::npos);
}

TEST_CASE("DslEmitCuda emit_primitive_device_header", "[dsl][emit][cuda]") {
    const Z29Expr::Ptr i = Z29Expr::var("i");
    const Z29Expr::Ptr c2 = Z29Expr::var("c2");
    const Z29Expr::Ptr c1 = Z29Expr::var("c1");
    const Z29Expr::Ptr c0 = Z29Expr::var("c0");
    const Z29Expr::Ptr body =
        Z29Expr::add(Z29Expr::add(Z29Expr::mul(Z29Expr::mul(c2, i), i), Z29Expr::mul(c1, i)), c0);
    const StatusOr<PrimitiveIr> prim =
        PrimitiveIr::make("poly2_mod29", "(i: Z29, c2: Z29, c1: Z29, c0: Z29) -> Z29", body);
    REQUIRE(prim.ok());

    const StatusOr<std::string> header = DslEmitCuda::emit_primitive_device_header(prim.value());
    REQUIRE(header.ok());
    REQUIRE(header.value().find("class Poly2Mod29Device") != std::string::npos);
    REQUIRE(header.value().find("PARCAE_HD static std::uint8_t eval(") != std::string::npos);
    REQUIRE(header.value().find("Z29Device::mul") != std::string::npos);
    REQUIRE(header.value().find("Poly2Mod29Device() = delete") != std::string::npos);
}

TEST_CASE("DslEmitCuda emit_expr atbash via Z29Device::sub", "[dsl][emit][cuda]") {
    const StatusOr<std::string> cpp =
        DslEmitCuda::emit_expr(Z29Expr::atbash(Z29Expr::var("x")), "x", "in[i]");
    REQUIRE(cpp.ok());
    REQUIRE(cpp.value() == "Z29Device::sub(static_cast<std::uint8_t>(28), in[i])");
}

TEST_CASE("DslEmitCuda emit_expr lowers Select via Z29Device::select",
          "[dsl][emit][cuda][select]") {
    const Z29Expr::Ptr expr =
        Z29Expr::select(Z29Expr::eq(Z29Expr::var("a"), Z29Expr::constant(1).value()),
                        Z29Expr::var("x"), Z29Expr::constant(7).value());
    const StatusOr<std::string> cpp = DslEmitCuda::emit_expr(expr, "x", "in[i]");
    REQUIRE(cpp.ok());
    REQUIRE(cpp.value().find("Z29Device::select(") != std::string::npos);
    REQUIRE(cpp.value().find("Z29Device::eq(") != std::string::npos);
}

TEST_CASE("DslEmitCuda prefer_branch Select emits divergent conditional",
          "[dsl][emit][cuda][select]") {
    const Z29Expr::Ptr expr =
        Z29Expr::select(Z29Expr::eq(Z29Expr::var("x"), Z29Expr::constant(0).value()),
                        Z29Expr::constant(1).value(), Z29Expr::constant(2).value(), true);
    const StatusOr<std::string> cpp = DslEmitCuda::emit_expr(expr, "x", "in[i]");
    REQUIRE(cpp.ok());
    REQUIRE(cpp.value().find("?") != std::string::npos);
    REQUIRE(cpp.value().find("Z29Device::select(") == std::string::npos);
}

TEST_CASE("DslEmitCuda rejects theory without steps", "[dsl][emit][cuda]") {
    const StatusOr<TheoryIr> theory =
        TheoryIr::make("no_steps", TheoryIr::Family::Elementwise, TheoryIr::Tier::A,
                       TheoryIr::InterruptMode::ElementwiseDefault, {});
    REQUIRE(theory.ok());
    REQUIRE_FALSE(DslEmitCuda::emit_theory_header(theory.value()).ok());
    REQUIRE_FALSE(DslEmitCuda::emit_theory_cu(theory.value()).ok());
}
