from typing import Any

class Z29Expr:
    def __init__(self, *_args: Any, **_kwargs: Any) -> None: ...
    def __add__(self, _other: Any) -> Z29Expr: ...
    def __radd__(self, _other: Any) -> Z29Expr: ...
    def __sub__(self, _other: Any) -> Z29Expr: ...
    def __rsub__(self, _other: Any) -> Z29Expr: ...
    def __mul__(self, _other: Any) -> Z29Expr: ...
    def __rmul__(self, _other: Any) -> Z29Expr: ...
    def __neg__(self) -> Z29Expr: ...

def z29_add(_x: Any, _y: Any) -> Z29Expr: ...
def z29_sub(_x: Any, _y: Any) -> Z29Expr: ...
def z29_mul(_x: Any, _y: Any) -> Z29Expr: ...
def z29_inv(_a: Any) -> Z29Expr: ...
def z29_mod(_x: Any, _y: Any) -> Z29Expr: ...
def z29_matmul(_matrix: Any, _rune_vec: Any) -> Z29Expr: ...
def z29_det(_matrix: Any) -> Z29Expr: ...
def z29_autokey_shift(_stream: Any, _lag: Any) -> Z29Expr: ...
