#ifndef DSL_EMIT_CUDA_HPP
#define DSL_EMIT_CUDA_HPP

#include "parcae/core/status.hpp"
#include "parcae/core/status_or.hpp"
#include "parcae/dsl/dsl_diag.hpp"
#include "parcae/dsl/dsl_emit_cpu.hpp"
#include "parcae/dsl/dsl_launch_plan.hpp"
#include "parcae/dsl/dsl_rule_id.hpp"
#include "parcae/dsl/matrix_ir.hpp"
#include "parcae/dsl/param_ir.hpp"
#include "parcae/dsl/primitive_ir.hpp"
#include "parcae/dsl/theory_ir.hpp"
#include "parcae/dsl/z29_expr.hpp"

#include <cctype>
#include <cstddef>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

/// Emit CUDA twin source text from DSL IR (`Z29Device` + Kernel façade).
/// Intended for `Parcae/Parcae/cuda/emitted/` (relative includes `../z29_device.hpp`, …).
class DslEmitCuda {
public:
    /// Lower Z29Expr to a device C++ expression using `Z29Device` / `uint8_t`.
    [[nodiscard]] static StatusOr<std::string> emit_expr(const Z29Expr::Ptr& expr,
                                                         std::string_view cipher_var = "x",
                                                         std::string_view cipher_cpp = "in[i]") {
        if (!expr) {
            return fail(DslRuleId::E032_primitive_body, "cannot emit null Z29Expr");
        }
        return emit_expr_rec(*expr, cipher_var, cipher_cpp);
    }

    /// Kernel façade header (`launch_device` / `apply_host`), CaesarKernel-shaped.
    [[nodiscard]] static StatusOr<std::string>
    emit_theory_header(const TheoryIr& theory, std::string_view cipher_var = "x") {
        Status prep = prepare_theory(theory);
        if (!prep.ok()) {
            return prep;
        }

        const std::string class_name = DslEmitCpu::to_pascal(theory.name()) + "Kernel";
        const std::string guard = to_guard(class_name);

        std::ostringstream out;
        out << "// Generated by parcae-compile (DslEmitCuda) — do not hand-edit.\n";
        out << "// theory_id=" << theory.name()
            << " family=" << TheoryIr::family_str(theory.family())
            << " tier=" << TheoryIr::tier_str(theory.tier()) << "\n";
        out << "#ifndef " << guard << "\n";
        out << "#define " << guard << "\n\n";
        out << "#include \"../params.hpp\"\n\n";
        out << "#include \"parcae/core/status.hpp\"\n\n";
        out << "#include <cstddef>\n";
        out << "#include <cstdint>\n";
        out << "#include <span>\n";
        out << "#include <string_view>\n\n";
        out << "/// Emitted CUDA twin for theory `" << theory.name() << "`.\n";
        out << "/// Uses Z29Device in the .cu; grid is 1D ceil(n/"
            << DslLaunchPlan::threads_per_block << ") (DslLaunchPlan / twin convention).\n";
        if (theory.interrupt_mode() == TheoryIr::InterruptMode::NoneByDesign) {
            out << "/// interrupts=none_by_design: device ignores skips; host apply MUST reject "
                   "non-empty InterruptPolicy.\n";
        } else {
            out << "/// Elementwise v0: interrupts unused on device (same as CaesarKernel); "
                   "host may still skip.\n";
        }
        out << "class " << class_name << " {\n";
        out << "public:\n";
        out << "    static constexpr std::string_view theory_id = \"" << theory.name() << "\";\n";
        out << "    static constexpr std::string_view interrupt_mode = \""
            << TheoryIr::interrupt_mode_str(theory.interrupt_mode()) << "\";\n\n";

        out << "    [[nodiscard]] static Status launch_device(\n";
        out << "        const std::uint8_t* device_in,\n";
        out << "        std::uint8_t* device_out,\n";
        out << "        std::size_t count,\n";
        for (const ParamIr& p : theory.params()) {
            out << "        std::uint8_t " << p.name() << ",\n";
        }
        out << "        CudaDir direction);\n\n";

        out << "    [[nodiscard]] static Status apply_host(\n";
        out << "        std::span<const std::uint8_t> host_in,\n";
        out << "        std::span<std::uint8_t> host_out,\n";
        for (const ParamIr& p : theory.params()) {
            out << "        std::uint8_t " << p.name() << ",\n";
        }
        out << "        CudaDir direction);\n\n";

        out << "private:\n";
        out << "    " << class_name << "() = delete;\n";
        out << "};\n\n";
        out << "#endif // " << guard << "\n";
        (void)cipher_var;
        return out.str();
    }

    /// `.cu` body: anonymous-namespace `__global__` kernel + launch/apply_host.
    [[nodiscard]] static StatusOr<std::string> emit_theory_cu(const TheoryIr& theory,
                                                              std::string_view cipher_var = "x") {
        Status prep = prepare_theory(theory);
        if (!prep.ok()) {
            return prep;
        }

        StatusOr<std::string> enc = emit_expr(theory.encrypt_step(), cipher_var, "in[i]");
        if (!enc.ok()) {
            return enc.status();
        }
        StatusOr<std::string> dec = emit_expr(theory.decrypt_step(), cipher_var, "in[i]");
        if (!dec.ok()) {
            return dec.status();
        }

        const bool need_autokey =
            expr_uses_autokey_shift(theory.encrypt_step()) ||
            expr_uses_autokey_shift(theory.decrypt_step());

        const std::string class_name = DslEmitCpu::to_pascal(theory.name()) + "Kernel";
        const std::string kern_fn = theory.name() + "_kernel";

        std::ostringstream out;
        out << "// Generated by parcae-compile (DslEmitCuda) — do not hand-edit.\n";
        out << "#include \"" << class_name << ".hpp\"\n\n";
        out << "#include \"../cuda_error.hpp\"\n";
        out << "#include \"../device_buffer.hpp\"\n";
        out << "#include \"../z29_device.hpp\"\n";
        if (need_autokey) {
            out << "#include \"../autokey_ring_device.hpp\"\n";
        }
        out << "\n";
        out << "#include <cuda_runtime_api.h>\n\n";
        out << "namespace {\n\n";
        out << "constexpr int kThreadsPerBlock = " << DslLaunchPlan::threads_per_block << ";\n\n";

        out << "__global__ void " << kern_fn << "(\n";
        out << "    const std::uint8_t* in,\n";
        out << "    std::uint8_t* out,\n";
        out << "    std::size_t count,\n";
        for (const ParamIr& p : theory.params()) {
            out << "    std::uint8_t " << p.name() << ",\n";
        }
        out << "    std::uint8_t encrypt) {\n";
        out << "    const std::size_t i =\n";
        out << "        static_cast<std::size_t>(blockIdx.x) * "
               "static_cast<std::size_t>(blockDim.x) +\n";
        out << "        static_cast<std::size_t>(threadIdx.x);\n";
        out << "    if (i >= count) {\n";
        out << "        return;\n";
        out << "    }\n";
        out << "    if (encrypt != 0u) {\n";
        out << "        out[i] = " << enc.value() << ";\n";
        out << "    } else {\n";
        out << "        out[i] = " << dec.value() << ";\n";
        out << "    }\n";
        out << "}\n\n";
        out << "}  // namespace\n\n";

        // launch_device
        out << "Status " << class_name << "::launch_device(\n";
        out << "    const std::uint8_t* device_in,\n";
        out << "    std::uint8_t* device_out,\n";
        out << "    std::size_t count,\n";
        for (const ParamIr& p : theory.params()) {
            out << "    std::uint8_t " << p.name() << ",\n";
        }
        out << "    CudaDir direction) {\n";
        for (const ParamIr& p : theory.params()) {
            out << "    if (" << p.name() << " > 28u) {\n";
            out << "        return Status::error(\"" << class_name << ": " << p.name()
                << " must be in 0..28\");\n";
            out << "    }\n";
            if (p.min() > 0) {
                out << "    if (" << p.name() << " < " << static_cast<int>(p.min()) << "u) {\n";
                out << "        return Status::error(\"" << class_name << ": " << p.name()
                    << " below domain min\");\n";
                out << "    }\n";
            }
            if (p.max() < 28) {
                out << "    if (" << p.name() << " > " << static_cast<int>(p.max()) << "u) {\n";
                out << "        return Status::error(\"" << class_name << ": " << p.name()
                    << " above domain max\");\n";
                out << "    }\n";
            }
        }
        out << "    if (count == 0) {\n";
        out << "        return Status::success();\n";
        out << "    }\n";
        out << "    if (device_in == nullptr || device_out == nullptr) {\n";
        out << "        return Status::error(\"" << class_name
            << "::launch_device null device pointer\");\n";
        out << "    }\n";
        out << "    const std::uint8_t encrypt =\n";
        out << "        direction == CudaDir::Encrypt ? static_cast<std::uint8_t>(1)\n";
        out << "                                      : static_cast<std::uint8_t>(0);\n";
        out << "    const int blocks = static_cast<int>(\n";
        out << "        (count + static_cast<std::size_t>(kThreadsPerBlock) - 1u) /\n";
        out << "        static_cast<std::size_t>(kThreadsPerBlock));\n";
        out << "    " << kern_fn << "<<<blocks, kThreadsPerBlock>>>(\n";
        out << "        device_in, device_out, count";
        for (const ParamIr& p : theory.params()) {
            out << ", " << p.name();
        }
        out << ", encrypt);\n";
        out << "    Status launch = CudaError::to_status(cudaGetLastError(), \"" << class_name
            << "::launch_device\");\n";
        out << "    if (!launch.ok()) {\n";
        out << "        return launch;\n";
        out << "    }\n";
        out << "    return CudaError::to_status(cudaDeviceSynchronize(), \"" << class_name
            << "::launch_device sync\");\n";
        out << "}\n\n";

        // apply_host
        out << "Status " << class_name << "::apply_host(\n";
        out << "    std::span<const std::uint8_t> host_in,\n";
        out << "    std::span<std::uint8_t> host_out,\n";
        for (const ParamIr& p : theory.params()) {
            out << "    std::uint8_t " << p.name() << ",\n";
        }
        out << "    CudaDir direction) {\n";
        out << "    if (host_in.size() != host_out.size()) {\n";
        out << "        return Status::error(\"" << class_name
            << "::apply_host size mismatch\");\n";
        out << "    }\n";
        out << "    if (host_in.data() == host_out.data()) {\n";
        out << "        StatusOr<DeviceBuffer<std::uint8_t>> device =\n";
        out << "            DeviceBuffer<std::uint8_t>::from_host(host_in);\n";
        out << "        if (!device.ok()) {\n";
        out << "            return device.status();\n";
        out << "        }\n";
        out << "        Status launched = launch_device(\n";
        out << "            device.value().data(), device.value().data(), host_in.size()";
        for (const ParamIr& p : theory.params()) {
            out << ", " << p.name();
        }
        out << ", direction);\n";
        out << "        if (!launched.ok()) {\n";
        out << "            return launched;\n";
        out << "        }\n";
        out << "        return device.value().copy_to_host(host_out);\n";
        out << "    }\n";
        out << "    StatusOr<DeviceBuffer<std::uint8_t>> device_in =\n";
        out << "        DeviceBuffer<std::uint8_t>::from_host(host_in);\n";
        out << "    if (!device_in.ok()) {\n";
        out << "        return device_in.status();\n";
        out << "    }\n";
        out << "    StatusOr<DeviceBuffer<std::uint8_t>> device_out =\n";
        out << "        DeviceBuffer<std::uint8_t>::allocate(host_out.size());\n";
        out << "    if (!device_out.ok()) {\n";
        out << "        return device_out.status();\n";
        out << "    }\n";
        out << "    Status launched = launch_device(\n";
        out << "        device_in.value().data(), device_out.value().data(), host_in.size()";
        for (const ParamIr& p : theory.params()) {
            out << ", " << p.name();
        }
        out << ", direction);\n";
        out << "    if (!launched.ok()) {\n";
        out << "        return launched;\n";
        out << "    }\n";
        out << "    return device_out.value().copy_to_host(host_out);\n";
        out << "}\n";
        return out.str();
    }

    /// Device helper header for a primitive (`PARCAE_HD` eval via Z29Device).
    [[nodiscard]] static StatusOr<std::string>
    emit_primitive_device_header(const PrimitiveIr& primitive) {
        Status st = primitive.validate();
        if (!st.ok()) {
            return st;
        }
        if (!is_safe_ident(primitive.name())) {
            return fail(DslRuleId::E032_primitive_body,
                        "primitive name '" + primitive.name() + "' is not a safe C++ identifier");
        }
        for (const std::string& n : primitive.param_names()) {
            if (!is_safe_ident(n)) {
                return fail(DslRuleId::E032_primitive_body,
                            "primitive param '" + n + "' is not a safe C++ identifier");
            }
        }

        StatusOr<std::string> body_cpp =
            emit_expr_rec(*primitive.body(), /*cipher_var=*/"", /*cipher_cpp=*/"");
        if (!body_cpp.ok()) {
            return body_cpp.status();
        }

        const std::string class_name = DslEmitCpu::to_pascal(primitive.name()) + "Device";
        const std::string guard = to_guard(class_name);

        std::ostringstream out;
        out << "// Generated by parcae-compile (DslEmitCuda) — do not hand-edit.\n";
        out << "#ifndef " << guard << "\n";
        out << "#define " << guard << "\n\n";
        out << "#include \"../z29_device.hpp\"\n\n";
        out << "#include <cstdint>\n";
        out << "#include <string_view>\n\n";
        out << "#if defined(__CUDACC__)\n";
        out << "#define PARCAE_HD __host__ __device__\n";
        out << "#else\n";
        out << "#define PARCAE_HD\n";
        out << "#endif\n\n";
        out << "class " << class_name << " {\n";
        out << "public:\n";
        out << "    static constexpr std::string_view primitive_id = \"" << primitive.name()
            << "\";\n\n";
        out << "    [[nodiscard]] PARCAE_HD static std::uint8_t eval(";
        for (std::size_t i = 0; i < primitive.param_names().size(); ++i) {
            if (i > 0) {
                out << ", ";
            }
            out << "std::uint8_t " << primitive.param_names()[i];
        }
        out << ") noexcept {\n";
        out << "        return " << body_cpp.value() << ";\n";
        out << "    }\n\n";
        out << "private:\n";
        out << "    " << class_name << "() = delete;\n";
        out << "};\n\n";
        out << "#undef PARCAE_HD\n\n";
        out << "#endif // " << guard << "\n";
        return out.str();
    }

private:
    DslEmitCuda() = delete;

    [[nodiscard]] static Status fail(std::string_view rule_id, std::string message) {
        return DslDiag::make(rule_id, std::move(message)).to_status();
    }

    [[nodiscard]] static bool is_safe_ident(std::string_view s) {
        if (s.empty()) {
            return false;
        }
        const unsigned char c0 = static_cast<unsigned char>(s[0]);
        if (!(std::isalpha(c0) || s[0] == '_')) {
            return false;
        }
        for (char ch : s) {
            const unsigned char c = static_cast<unsigned char>(ch);
            if (!(std::isalnum(c) || ch == '_')) {
                return false;
            }
        }
        return true;
    }

    [[nodiscard]] static std::string to_guard(std::string_view class_name) {
        std::string g;
        for (char ch : class_name) {
            const unsigned char c = static_cast<unsigned char>(ch);
            if (std::isalnum(c)) {
                g.push_back(static_cast<char>(std::toupper(c)));
            } else {
                g.push_back('_');
            }
        }
        g += "_HPP";
        return g;
    }

    [[nodiscard]] static Status prepare_theory(const TheoryIr& theory) {
        if (theory.name().empty()) {
            return fail(DslRuleId::E032_primitive_body, "theory name must be non-empty");
        }
        if (!is_safe_ident(theory.name())) {
            return fail(DslRuleId::E032_primitive_body,
                        "theory name '" + theory.name() + "' is not a safe C++ identifier base");
        }
        if (!theory.encrypt_step() || !theory.decrypt_step()) {
            return fail(DslRuleId::E032_primitive_body,
                        "theory '" + theory.name() +
                            "' needs encrypt_step and decrypt_step to emit CUDA");
        }
        for (const ParamIr& p : theory.params()) {
            if (!is_safe_ident(p.name())) {
                return fail(DslRuleId::E040_param_domain,
                            "param '" + p.name() + "' is not a safe C++ identifier");
            }
        }
        return Status::success();
    }

    [[nodiscard]] static StatusOr<std::string>
    emit_expr_rec(const Z29Expr& expr, std::string_view cipher_var, std::string_view cipher_cpp) {
        using Kind = Z29Expr::Kind;
        switch (expr.kind()) {
        case Kind::Const:
            return std::string("static_cast<std::uint8_t>(") + std::to_string(expr.const_value()) +
                   ")";
        case Kind::Var: {
            if (!cipher_var.empty() && expr.name() == cipher_var) {
                if (cipher_cpp.empty()) {
                    return fail(DslRuleId::E032_primitive_body,
                                "cipher_var used but cipher_cpp is empty");
                }
                return std::string(cipher_cpp);
            }
            if (!is_safe_ident(expr.name())) {
                return fail(DslRuleId::E032_primitive_body,
                            "unsafe var name '" + expr.name() + "' in CUDA emit");
            }
            return expr.name();
        }
        case Kind::Call: {
            const std::string& n = expr.name();
            const auto& args = expr.args();
            auto as_bin = [&](Z29Expr::Kind k) -> StatusOr<std::string> {
                if (args.size() != 2 || !args[0] || !args[1]) {
                    return fail(DslRuleId::E032_primitive_body, "call arity for CUDA emit");
                }
                return emit_expr_rec(*Z29Expr::make_binary(k, args[0], args[1]), cipher_var,
                                     cipher_cpp);
            };
            auto as_unary = [&](Z29Expr::Kind k) -> StatusOr<std::string> {
                if (args.size() != 1 || !args[0]) {
                    return fail(DslRuleId::E032_primitive_body, "call arity for CUDA emit");
                }
                return emit_expr_rec(*Z29Expr::make_unary_kind(k, args[0]), cipher_var, cipher_cpp);
            };
            if (n == "z29_add") {
                return as_bin(Kind::Add);
            }
            if (n == "z29_sub") {
                return as_bin(Kind::Sub);
            }
            if (n == "z29_mul") {
                return as_bin(Kind::Mul);
            }
            if (n == "z29_div") {
                return as_bin(Kind::Div);
            }
            if (n == "z29_floordiv") {
                return as_bin(Kind::FloorDiv);
            }
            if (n == "z29_mod") {
                return as_bin(Kind::Mod);
            }
            if (n == "z29_pow") {
                return as_bin(Kind::Pow);
            }
            if (n == "z29_bit_and") {
                return as_bin(Kind::BitAnd);
            }
            if (n == "z29_bit_or") {
                return as_bin(Kind::BitOr);
            }
            if (n == "z29_bit_xor") {
                return as_bin(Kind::BitXor);
            }
            if (n == "z29_lshift") {
                return as_bin(Kind::LShift);
            }
            if (n == "z29_rshift") {
                return as_bin(Kind::RShift);
            }
            if (n == "z29_eq") {
                return as_bin(Kind::Eq);
            }
            if (n == "z29_ne") {
                return as_bin(Kind::Ne);
            }
            if (n == "z29_lt") {
                return as_bin(Kind::Lt);
            }
            if (n == "z29_le") {
                return as_bin(Kind::Le);
            }
            if (n == "z29_gt") {
                return as_bin(Kind::Gt);
            }
            if (n == "z29_ge") {
                return as_bin(Kind::Ge);
            }
            if (n == "z29_bool_and") {
                return as_bin(Kind::BoolAnd);
            }
            if (n == "z29_bool_or") {
                return as_bin(Kind::BoolOr);
            }
            if (n == "z29_inv") {
                return as_unary(Kind::Inv);
            }
            if (n == "z29_neg") {
                return as_unary(Kind::Neg);
            }
            if (n == "z29_atbash") {
                return as_unary(Kind::Atbash);
            }
            if (n == "z29_bit_not") {
                return as_unary(Kind::BitNot);
            }
            if (n == "z29_bool_not") {
                return as_unary(Kind::BoolNot);
            }
            if (n == "z29_select") {
                if (args.size() != 3 || !args[0] || !args[1] || !args[2]) {
                    return fail(DslRuleId::E032_primitive_body, "z29_select arity for CUDA emit");
                }
                return emit_expr_rec(*Z29Expr::make_select(args[0], args[1], args[2]), cipher_var,
                                     cipher_cpp);
            }
            if (n == "z29_det") {
                return emit_z29_det_call(args, cipher_var, cipher_cpp);
            }
            if (n == "z29_matmul") {
                return emit_z29_matmul_call(args, cipher_var, cipher_cpp);
            }
            if (n == "z29_autokey_shift") {
                return emit_z29_autokey_shift_call(args, cipher_var, cipher_cpp);
            }
            return fail(DslRuleId::E032_primitive_body,
                        "cannot CUDA-emit unknown primitive call '" + n + "'");
        }
        case Kind::Select: {
            if (!expr.cond() || !expr.if_true() || !expr.if_false()) {
                return fail(DslRuleId::E032_primitive_body, "Select missing operands");
            }
            StatusOr<std::string> c = emit_expr_rec(*expr.cond(), cipher_var, cipher_cpp);
            if (!c.ok()) {
                return c.status();
            }
            StatusOr<std::string> t = emit_expr_rec(*expr.if_true(), cipher_var, cipher_cpp);
            if (!t.ok()) {
                return t.status();
            }
            StatusOr<std::string> f = emit_expr_rec(*expr.if_false(), cipher_var, cipher_cpp);
            if (!f.ok()) {
                return f.status();
            }
            if (expr.prefer_branch()) {
                // Honored divergent_branch: predicated/real if (warp-divergence risk).
                return std::string("((") + c.value() + " != 0u) ? (" + t.value() + ") : (" +
                       f.value() + "))";
            }
            return std::string("Z29Device::select(") + c.value() + ", " + t.value() + ", " +
                   f.value() + ")";
        }
        default:
            break;
        }
        if (Z29Expr::is_binary(expr.kind())) {
            if (!expr.left() || !expr.right()) {
                return fail(DslRuleId::E032_primitive_body, "binary expr missing operands");
            }
            StatusOr<std::string> l = emit_expr_rec(*expr.left(), cipher_var, cipher_cpp);
            if (!l.ok()) {
                return l.status();
            }
            StatusOr<std::string> r = emit_expr_rec(*expr.right(), cipher_var, cipher_cpp);
            if (!r.ok()) {
                return r.status();
            }
            switch (expr.kind()) {
            case Kind::Add:
                return std::string("Z29Device::add(") + l.value() + ", " + r.value() + ")";
            case Kind::Sub:
                return std::string("Z29Device::sub(") + l.value() + ", " + r.value() + ")";
            case Kind::Mul:
                return std::string("Z29Device::mul(") + l.value() + ", " + r.value() + ")";
            case Kind::Div:
                return std::string("Z29Device::mul(") + l.value() + ", Z29Device::inv(" +
                       r.value() + "))";
            case Kind::FloorDiv:
                return std::string("Z29Device::floor_div(") + l.value() + ", " + r.value() + ")";
            case Kind::Mod:
                return std::string("static_cast<std::uint8_t>((") + l.value() + " % " + r.value() +
                       "))";
            case Kind::Pow:
                return std::string("Z29Device::pow(") + l.value() + ", " + r.value() + ")";
            case Kind::BitAnd:
                return std::string("Z29Device::bit_and(") + l.value() + ", " + r.value() + ")";
            case Kind::BitOr:
                return std::string("Z29Device::bit_or(") + l.value() + ", " + r.value() + ")";
            case Kind::BitXor:
                return std::string("Z29Device::bit_xor(") + l.value() + ", " + r.value() + ")";
            case Kind::LShift:
                return std::string("Z29Device::lshift(") + l.value() + ", " + r.value() + ")";
            case Kind::RShift:
                return std::string("Z29Device::rshift(") + l.value() + ", " + r.value() + ")";
            case Kind::Eq:
                return std::string("Z29Device::eq(") + l.value() + ", " + r.value() + ")";
            case Kind::Ne:
                return std::string("Z29Device::ne(") + l.value() + ", " + r.value() + ")";
            case Kind::Lt:
                return std::string("Z29Device::lt(") + l.value() + ", " + r.value() + ")";
            case Kind::Le:
                return std::string("Z29Device::le(") + l.value() + ", " + r.value() + ")";
            case Kind::Gt:
                return std::string("Z29Device::gt(") + l.value() + ", " + r.value() + ")";
            case Kind::Ge:
                return std::string("Z29Device::ge(") + l.value() + ", " + r.value() + ")";
            case Kind::BoolAnd:
                return std::string("Z29Device::bool_and(") + l.value() + ", " + r.value() + ")";
            case Kind::BoolOr:
                return std::string("Z29Device::bool_or(") + l.value() + ", " + r.value() + ")";
            default:
                break;
            }
        }
        if (Z29Expr::is_unary(expr.kind())) {
            if (!expr.arg()) {
                return fail(DslRuleId::E032_primitive_body, "unary expr missing operand");
            }
            StatusOr<std::string> a = emit_expr_rec(*expr.arg(), cipher_var, cipher_cpp);
            if (!a.ok()) {
                return a.status();
            }
            switch (expr.kind()) {
            case Kind::Neg:
                return std::string("Z29Device::neg(") + a.value() + ")";
            case Kind::Inv:
                return std::string("Z29Device::inv(") + a.value() + ")";
            case Kind::Atbash:
            case Kind::BitNot:
                return std::string("Z29Device::sub(static_cast<std::uint8_t>(28), ") + a.value() +
                       ")";
            case Kind::BoolNot:
                return std::string("Z29Device::bool_not(") + a.value() + ")";
            default:
                break;
            }
        }
        return fail(DslRuleId::E032_primitive_body, "unknown Z29Expr kind in CUDA emit");
    }

    /// Flattened `z29_det` Call → expand `MatrixIr::det_expr()` then emit via Z29Device.
    [[nodiscard]] static StatusOr<std::string>
    emit_z29_det_call(const std::vector<Z29Expr::Ptr>& args, std::string_view cipher_var,
                      std::string_view cipher_cpp) {
        if (args.size() != 4 && args.size() != 9) {
            return fail(DslRuleId::E032_primitive_body,
                        "z29_det Call CUDA emit expects 4 or 9 flattened matrix entries");
        }
        StatusOr<MatrixIr> matrix = MatrixIr::make(args);
        if (!matrix.ok()) {
            return matrix.status();
        }
        return emit_expr_rec(*matrix.value().det_expr(), cipher_var, cipher_cpp);
    }

    /// Flattened `z29_matmul` (n²+n) → emit component 0 of `mul_vec` via MatrixIr expand.
    [[nodiscard]] static StatusOr<std::string>
    emit_z29_matmul_call(const std::vector<Z29Expr::Ptr>& args, std::string_view cipher_var,
                         std::string_view cipher_cpp) {
        std::size_t n = 0;
        if (args.size() == 6) {
            n = 2;
        } else if (args.size() == 12) {
            n = 3;
        } else {
            return fail(DslRuleId::E032_primitive_body,
                        "z29_matmul Call CUDA emit expects 6 (2x2) or 12 (3x3) flattened entries "
                        "(matrix then vector); prefer BuildIr z29_matmul(...)[i]");
        }
        std::vector<Z29Expr::Ptr> matrix_entries(args.begin(),
                                                 args.begin() + static_cast<std::ptrdiff_t>(n * n));
        StatusOr<MatrixIr> matrix = MatrixIr::make(matrix_entries);
        if (!matrix.ok()) {
            return matrix.status();
        }
        std::vector<Z29Expr::Ptr> vec(args.begin() + static_cast<std::ptrdiff_t>(n * n), args.end());
        StatusOr<Z29Expr::Ptr> comp = matrix.value().mul_vec_component(vec, 0);
        if (!comp.ok()) {
            return comp.status();
        }
        return emit_expr_rec(*comp.value(), cipher_var, cipher_cpp);
    }

    /// `z29_autokey_shift(stream, lag)` → `AutokeyRingDevice::shift(in, i, lag)`.
    [[nodiscard]] static StatusOr<std::string>
    emit_z29_autokey_shift_call(const std::vector<Z29Expr::Ptr>& args, std::string_view cipher_var,
                                std::string_view cipher_cpp) {
        if (args.size() != 2 || !args[0] || !args[1]) {
            return fail(DslRuleId::E032_primitive_body,
                        "z29_autokey_shift expects (stream, lag)");
        }
        if (args[0]->kind() != Z29Expr::Kind::Var || args[0]->name() != cipher_var) {
            return fail(DslRuleId::E032_primitive_body,
                        "z29_autokey_shift stream must be the HotLoop cipher var '" +
                            std::string(cipher_var) + "'");
        }
        StatusOr<std::string> base = DslEmitCpu::stream_base_from_cipher_cpp(cipher_cpp);
        if (!base.ok()) {
            return base.status();
        }
        StatusOr<std::string> lag = emit_expr_rec(*args[1], cipher_var, cipher_cpp);
        if (!lag.ok()) {
            return lag.status();
        }
        return std::string("AutokeyRingDevice::shift(") + base.value() + ", i, " + lag.value() +
               ")";
    }

    [[nodiscard]] static bool expr_uses_autokey_shift(const Z29Expr::Ptr& expr) {
        if (!expr) {
            return false;
        }
        using Kind = Z29Expr::Kind;
        if (expr->kind() == Kind::Call) {
            if (expr->name() == "z29_autokey_shift") {
                return true;
            }
            for (const Z29Expr::Ptr& a : expr->args()) {
                if (expr_uses_autokey_shift(a)) {
                    return true;
                }
            }
            return false;
        }
        if (expr->kind() == Kind::Select) {
            return expr_uses_autokey_shift(expr->cond()) ||
                   expr_uses_autokey_shift(expr->if_true()) ||
                   expr_uses_autokey_shift(expr->if_false());
        }
        if (Z29Expr::is_binary(expr->kind())) {
            return expr_uses_autokey_shift(expr->left()) || expr_uses_autokey_shift(expr->right());
        }
        if (Z29Expr::is_unary(expr->kind())) {
            return expr_uses_autokey_shift(expr->arg());
        }
        return false;
    }
};

#endif // DSL_EMIT_CUDA_HPP
