#ifndef DSL_EMIT_CPU_HPP
#define DSL_EMIT_CPU_HPP

#include "parcae/core/status.hpp"
#include "parcae/core/status_or.hpp"
#include "parcae/dsl/dsl_diag.hpp"
#include "parcae/dsl/dsl_rule_id.hpp"
#include "parcae/dsl/matrix_ir.hpp"
#include "parcae/dsl/param_ir.hpp"
#include "parcae/dsl/primitive_ir.hpp"
#include "parcae/dsl/theory_ir.hpp"
#include "parcae/dsl/z29_expr.hpp"

#include <cctype>
#include <cstddef>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>

/// Emit Transform-shaped C++ header text from DSL IR (docs/architecture/python-transpiler.md).
/// Output is a standalone class (not Force-registered in TransformId yet); shape matches
/// `apply_into` / interrupt pass-through used by hand transforms + DslIrApplicator.
class DslEmitCpu {
public:
    /// Lower one Z29Expr to a C++ expression using host `Z29` / `Index29`.
    /// `cipher_var` binds to `cipher_cpp` (default `input[i]`).
    [[nodiscard]] static StatusOr<std::string> emit_expr(const Z29Expr::Ptr& expr,
                                                         std::string_view cipher_var = "x",
                                                         std::string_view cipher_cpp = "input[i]") {
        if (!expr) {
            return fail(DslRuleId::E032_primitive_body, "cannot emit null Z29Expr");
        }
        return emit_expr_rec(*expr, cipher_var, cipher_cpp);
    }

    /// Full header: `#ifndef …` + `class <Pascal>Transform` with encrypt/decrypt kernels.
    [[nodiscard]] static StatusOr<std::string>
    emit_theory_header(const TheoryIr& theory, std::string_view cipher_var = "x") {
        if (theory.name().empty()) {
            return fail(DslRuleId::E032_primitive_body, "theory name must be non-empty");
        }
        if (!is_safe_ident(theory.name())) {
            return fail(DslRuleId::E032_primitive_body,
                        "theory name '" + theory.name() +
                            "' is not a safe C++ identifier base ([a-z][a-z0-9_]*)");
        }
        if (!theory.encrypt_step() || !theory.decrypt_step()) {
            return fail(DslRuleId::E032_primitive_body,
                        "theory '" + theory.name() +
                            "' needs encrypt_step and decrypt_step to emit CPU");
        }
        for (const ParamIr& p : theory.params()) {
            if (!is_safe_ident(p.name())) {
                return fail(DslRuleId::E040_param_domain,
                            "param '" + p.name() + "' is not a safe C++ identifier");
            }
        }

        StatusOr<std::string> enc = emit_expr(theory.encrypt_step(), cipher_var, "input[i]");
        if (!enc.ok()) {
            return enc.status();
        }
        StatusOr<std::string> dec = emit_expr(theory.decrypt_step(), cipher_var, "input[i]");
        if (!dec.ok()) {
            return dec.status();
        }

        const std::string class_name = to_pascal(theory.name()) + "Transform";
        const std::string guard = to_guard(class_name);

        std::ostringstream out;
        out << "// Generated by parcae-compile (DslEmitCpu) — do not hand-edit.\n";
        out << "// theory_id=" << theory.name()
            << " family=" << TheoryIr::family_str(theory.family())
            << " tier=" << TheoryIr::tier_str(theory.tier()) << "\n";
        out << "#ifndef " << guard << "\n";
        out << "#define " << guard << "\n\n";
        out << "#include \"parcae/core/index29.hpp\"\n";
        out << "#include \"parcae/core/status.hpp\"\n";
        out << "#include \"parcae/core/status_or.hpp\"\n";
        out << "#include \"parcae/core/z29.hpp\"\n";
        out << "#include \"parcae/math/autokey_ring.hpp\"\n";
        out << "#include \"parcae/math/z29_matrix2.hpp\"\n";
        out << "#include \"parcae/math/z29_matrix3.hpp\"\n";
        out << "#include \"parcae/interrupt/policy.hpp\"\n";
        out << "#include \"parcae/transform/transform_buffer.hpp\"\n";
        out << "#include \"parcae/transform/transform_direction.hpp\"\n\n";
        out << "#include <array>\n";
        out << "#include <cstdint>\n";
        out << "#include <span>\n";
        out << "#include <string>\n";
        out << "#include <string_view>\n";
        out << "#include <vector>\n\n";
        out << "#include <nlohmann/json.hpp>\n\n";
        out << "/// Emitted CPU transform for theory `" << theory.name() << "`.\n";
        out << "/// Transform-shaped (`apply_into`); not yet a TransformId catalog entry.\n";
        out << "class " << class_name << " {\n";
        out << "public:\n";
        out << "    static constexpr std::string_view theory_id = \"" << theory.name() << "\";\n";
        out << "    static constexpr std::string_view interrupt_mode = \""
            << TheoryIr::interrupt_mode_str(theory.interrupt_mode()) << "\";\n\n";
        out << "    " << class_name << "() = default;\n\n";

        // kernel
        out << "    [[nodiscard]] static Status kernel(\n";
        out << "        std::span<const Index29> input,\n";
        out << "        std::span<Index29> output,\n";
        for (const ParamIr& p : theory.params()) {
            out << "        Index29 " << p.name() << ",\n";
        }
        out << "        TransformDirection direction,\n";
        out << "        std::span<const std::size_t> skip_indices_sorted) {\n";
        out << "        Status sizes = TransformBuffer::require_same_length(input, output);\n";
        out << "        if (!sizes.ok()) {\n";
        out << "            return sizes;\n";
        out << "        }\n";
        out << "        for (std::size_t i = 0; i < input.size(); ++i) {\n";
        out << "            if (TransformBuffer::should_skip(skip_indices_sorted, i)) {\n";
        out << "                output[i] = input[i];\n";
        out << "                continue;\n";
        out << "            }\n";
        out << "            if (direction == TransformDirection::Encrypt) {\n";
        out << "                output[i] = " << enc.value() << ";\n";
        out << "            } else {\n";
        out << "                output[i] = " << dec.value() << ";\n";
        out << "            }\n";
        out << "        }\n";
        out << "        return Status::success();\n";
        out << "    }\n\n";

        // apply_into
        out << "    [[nodiscard]] static Status apply_into(\n";
        out << "        std::span<const Index29> input,\n";
        out << "        std::span<Index29> output,\n";
        out << "        const nlohmann::json& params,\n";
        out << "        TransformDirection direction,\n";
        out << "        const InterruptPolicy& interrupt = InterruptPolicy::none()) {\n";
        out << "        StatusOr<ParsedParams> parsed = parse_params(params);\n";
        out << "        if (!parsed.ok()) {\n";
        out << "            return parsed.status();\n";
        out << "        }\n";
        out << "        Status range = TransformBuffer::validate_interrupt_range(\n";
        out << "            interrupt, input.size(), \"" << theory.name() << "\");\n";
        out << "        if (!range.ok()) {\n";
        out << "            return range;\n";
        out << "        }\n";
        if (theory.interrupt_mode() == TheoryIr::InterruptMode::NoneByDesign) {
            out << "        if (!interrupt.empty()) {\n";
            out << "            return Status::error(\"" << theory.name()
                << ": interrupts=none_by_design rejects non-empty InterruptPolicy "
                   "(CPU↔CUDA parity)\");\n";
            out << "        }\n";
        }
        out << "        return kernel(\n";
        out << "            input,\n";
        out << "            output,\n";
        for (const ParamIr& p : theory.params()) {
            out << "            parsed.value()." << p.name() << ",\n";
        }
        out << "            direction,\n";
        out << "            TransformBuffer::skip_span(interrupt));\n";
        out << "    }\n\n";

        out << "    [[nodiscard]] static StatusOr<std::vector<Index29>> apply(\n";
        out << "        std::span<const Index29> input,\n";
        out << "        const nlohmann::json& params,\n";
        out << "        TransformDirection direction,\n";
        out << "        const InterruptPolicy& interrupt = InterruptPolicy::none()) {\n";
        out << "        std::vector<Index29> out(input.size());\n";
        out << "        Status st = apply_into(input, out, params, direction, interrupt);\n";
        out << "        if (!st.ok()) {\n";
        out << "            return st;\n";
        out << "        }\n";
        out << "        return out;\n";
        out << "    }\n\n";

        out << "private:\n";
        out << "    struct ParsedParams {\n";
        for (const ParamIr& p : theory.params()) {
            out << "        Index29 " << p.name() << "{};\n";
        }
        out << "    };\n\n";

        out << "    [[nodiscard]] static StatusOr<ParsedParams> parse_params(const nlohmann::json& "
               "params) {\n";
        out << "        if (!params.is_object()) {\n";
        out << "            return Status::error(\"" << theory.name()
            << " params must be an object\");\n";
        out << "        }\n";
        out << "        if (params.size() != " << theory.params().size() << ") {\n";
        out << "            return Status::error(\"" << theory.name()
            << " params has unexpected size\");\n";
        out << "        }\n";
        out << "        ParsedParams out;\n";
        for (const ParamIr& p : theory.params()) {
            out << "        {\n";
            out << "            if (!params.contains(\"" << p.name() << "\")) {\n";
            out << "                return Status::error(\"" << theory.name() << " params."
                << p.name() << " is required\");\n";
            out << "            }\n";
            out << "            if (!params.at(\"" << p.name() << "\").is_number_integer()) {\n";
            out << "                return Status::error(\"" << theory.name() << " params."
                << p.name() << " must be an integer\");\n";
            out << "            }\n";
            out << "            const auto raw = params.at(\"" << p.name()
                << "\").get<std::int64_t>();\n";
            out << "            if (raw < " << static_cast<int>(p.min()) << " || raw > "
                << static_cast<int>(p.max()) << ") {\n";
            out << "                return Status::error(\"" << theory.name() << " params."
                << p.name() << " out of domain\");\n";
            out << "            }\n";
            out << "            out." << p.name()
                << " = Index29{static_cast<std::uint8_t>(raw)};\n";
            out << "        }\n";
        }
        out << "        return out;\n";
        out << "    }\n";
        out << "};\n\n";
        out << "#endif // " << guard << "\n";
        return out.str();
    }

    /// Header with a static `eval` for a `@define_primitive` body (arity args).
    [[nodiscard]] static StatusOr<std::string> emit_primitive_header(const PrimitiveIr& primitive) {
        Status st = primitive.validate();
        if (!st.ok()) {
            return st;
        }
        if (!is_safe_ident(primitive.name())) {
            return fail(DslRuleId::E032_primitive_body,
                        "primitive name '" + primitive.name() + "' is not a safe C++ identifier");
        }
        for (const std::string& n : primitive.param_names()) {
            if (!is_safe_ident(n)) {
                return fail(DslRuleId::E032_primitive_body,
                            "primitive param '" + n + "' is not a safe C++ identifier");
            }
        }

        // For primitives, every param is a C++ Index29 argument (no cipher stream).
        StatusOr<std::string> body_cpp =
            emit_expr_rec(*primitive.body(), /*cipher_var=*/"", /*cipher_cpp=*/"");
        if (!body_cpp.ok()) {
            return body_cpp.status();
        }

        const std::string class_name = to_pascal(primitive.name()) + "Primitive";
        const std::string guard = to_guard(class_name);

        std::ostringstream out;
        out << "// Generated by parcae-compile (DslEmitCpu) — do not hand-edit.\n";
        out << "#ifndef " << guard << "\n";
        out << "#define " << guard << "\n\n";
        out << "#include \"parcae/core/index29.hpp\"\n";
        out << "#include \"parcae/core/status.hpp\"\n";
        out << "#include \"parcae/core/status_or.hpp\"\n";
        out << "#include \"parcae/core/z29.hpp\"\n";
        out << "#include \"parcae/math/z29_matrix2.hpp\"\n";
        out << "#include \"parcae/math/z29_matrix3.hpp\"\n";
        out << "#include <array>\n";
        out << "#include <string_view>\n\n";
        out << "class " << class_name << " {\n";
        out << "public:\n";
        out << "    static constexpr std::string_view primitive_id = \"" << primitive.name()
            << "\";\n\n";
        out << "    [[nodiscard]] static Index29 eval(";
        for (std::size_t i = 0; i < primitive.param_names().size(); ++i) {
            if (i > 0) {
                out << ", ";
            }
            out << "Index29 " << primitive.param_names()[i];
        }
        out << ") {\n";
        out << "        return " << body_cpp.value() << ";\n";
        out << "    }\n";
        out << "};\n\n";
        out << "#endif // " << guard << "\n";
        return out.str();
    }

    [[nodiscard]] static std::string to_pascal(std::string_view snake) {
        std::string out;
        bool upper = true;
        for (char ch : snake) {
            if (ch == '_') {
                upper = true;
                continue;
            }
            if (upper) {
                out.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(ch))));
                upper = false;
            } else {
                out.push_back(ch);
            }
        }
        return out;
    }

    /// `input[i]` / `in[i]` → `input` / `in` (for `z29_autokey_shift` stream base).
    [[nodiscard]] static StatusOr<std::string>
    stream_base_from_cipher_cpp(std::string_view cipher_cpp) {
        constexpr std::string_view suffix = "[i]";
        if (cipher_cpp.size() <= suffix.size() ||
            cipher_cpp.substr(cipher_cpp.size() - suffix.size()) != suffix) {
            return fail(DslRuleId::E032_primitive_body,
                        "z29_autokey_shift requires cipher_cpp ending in [i] (got '" +
                            std::string(cipher_cpp) + "')");
        }
        return std::string(cipher_cpp.substr(0, cipher_cpp.size() - suffix.size()));
    }

private:
    DslEmitCpu() = delete;

    [[nodiscard]] static Status fail(std::string_view rule_id, std::string message) {
        return DslDiag::make(rule_id, std::move(message)).to_status();
    }

    [[nodiscard]] static bool is_safe_ident(std::string_view s) {
        if (s.empty()) {
            return false;
        }
        const unsigned char c0 = static_cast<unsigned char>(s[0]);
        if (!(std::islower(c0) || s[0] == '_')) {
            // allow leading underscore; theory ids recommended [a-z]…
            if (!std::isalpha(c0) && s[0] != '_') {
                return false;
            }
        }
        for (char ch : s) {
            const unsigned char c = static_cast<unsigned char>(ch);
            if (!(std::isalnum(c) || ch == '_')) {
                return false;
            }
        }
        return true;
    }

    [[nodiscard]] static std::string to_guard(std::string_view class_name) {
        std::string g;
        for (char ch : class_name) {
            const unsigned char c = static_cast<unsigned char>(ch);
            if (std::isalnum(c)) {
                g.push_back(static_cast<char>(std::toupper(c)));
            } else {
                g.push_back('_');
            }
        }
        g += "_HPP";
        return g;
    }

    [[nodiscard]] static StatusOr<std::string>
    emit_expr_rec(const Z29Expr& expr, std::string_view cipher_var, std::string_view cipher_cpp) {
        using Kind = Z29Expr::Kind;
        switch (expr.kind()) {
        case Kind::Const:
            return std::string("Index29{") + std::to_string(expr.const_value()) + "u}";
        case Kind::Var: {
            if (!cipher_var.empty() && expr.name() == cipher_var) {
                if (cipher_cpp.empty()) {
                    return fail(DslRuleId::E032_primitive_body,
                                "cipher_var used but cipher_cpp is empty");
                }
                return std::string(cipher_cpp);
            }
            if (!is_safe_ident(expr.name())) {
                return fail(DslRuleId::E032_primitive_body,
                            "unsafe var name '" + expr.name() + "' in emit");
            }
            return expr.name();
        }
        case Kind::Call: {
            const std::string& n = expr.name();
            const auto& args = expr.args();
            auto as_bin = [&](Z29Expr::Kind k) -> StatusOr<std::string> {
                if (args.size() != 2 || !args[0] || !args[1]) {
                    return fail(DslRuleId::E032_primitive_body, "call arity for emit");
                }
                return emit_expr_rec(*Z29Expr::make_binary(k, args[0], args[1]), cipher_var,
                                     cipher_cpp);
            };
            auto as_unary = [&](Z29Expr::Kind k) -> StatusOr<std::string> {
                if (args.size() != 1 || !args[0]) {
                    return fail(DslRuleId::E032_primitive_body, "call arity for emit");
                }
                return emit_expr_rec(*Z29Expr::make_unary_kind(k, args[0]), cipher_var, cipher_cpp);
            };
            if (n == "z29_add") {
                return as_bin(Kind::Add);
            }
            if (n == "z29_sub") {
                return as_bin(Kind::Sub);
            }
            if (n == "z29_mul") {
                return as_bin(Kind::Mul);
            }
            if (n == "z29_div") {
                return as_bin(Kind::Div);
            }
            if (n == "z29_floordiv") {
                return as_bin(Kind::FloorDiv);
            }
            if (n == "z29_mod") {
                return as_bin(Kind::Mod);
            }
            if (n == "z29_pow") {
                return as_bin(Kind::Pow);
            }
            if (n == "z29_bit_and") {
                return as_bin(Kind::BitAnd);
            }
            if (n == "z29_bit_or") {
                return as_bin(Kind::BitOr);
            }
            if (n == "z29_bit_xor") {
                return as_bin(Kind::BitXor);
            }
            if (n == "z29_lshift") {
                return as_bin(Kind::LShift);
            }
            if (n == "z29_rshift") {
                return as_bin(Kind::RShift);
            }
            if (n == "z29_eq") {
                return as_bin(Kind::Eq);
            }
            if (n == "z29_ne") {
                return as_bin(Kind::Ne);
            }
            if (n == "z29_lt") {
                return as_bin(Kind::Lt);
            }
            if (n == "z29_le") {
                return as_bin(Kind::Le);
            }
            if (n == "z29_gt") {
                return as_bin(Kind::Gt);
            }
            if (n == "z29_ge") {
                return as_bin(Kind::Ge);
            }
            if (n == "z29_bool_and") {
                return as_bin(Kind::BoolAnd);
            }
            if (n == "z29_bool_or") {
                return as_bin(Kind::BoolOr);
            }
            if (n == "z29_inv") {
                return as_unary(Kind::Inv);
            }
            if (n == "z29_neg") {
                return as_unary(Kind::Neg);
            }
            if (n == "z29_atbash") {
                return as_unary(Kind::Atbash);
            }
            if (n == "z29_bit_not") {
                return as_unary(Kind::BitNot);
            }
            if (n == "z29_bool_not") {
                return as_unary(Kind::BoolNot);
            }
            if (n == "z29_select") {
                if (args.size() != 3 || !args[0] || !args[1] || !args[2]) {
                    return fail(DslRuleId::E032_primitive_body, "z29_select arity for emit");
                }
                return emit_expr_rec(*Z29Expr::make_select(args[0], args[1], args[2]), cipher_var,
                                     cipher_cpp);
            }
            if (n == "z29_det") {
                return emit_z29_det_call(args, cipher_var, cipher_cpp);
            }
            if (n == "z29_matmul") {
                return emit_z29_matmul_call(args, cipher_var, cipher_cpp);
            }
            if (n == "z29_autokey_shift") {
                return emit_z29_autokey_shift_call(args, cipher_var, cipher_cpp);
            }
            return fail(DslRuleId::E032_primitive_body,
                        "cannot emit unknown primitive call '" + n + "'");
        }
        case Kind::Select: {
            if (!expr.cond() || !expr.if_true() || !expr.if_false()) {
                return fail(DslRuleId::E032_primitive_body, "Select missing operands");
            }
            StatusOr<std::string> c = emit_expr_rec(*expr.cond(), cipher_var, cipher_cpp);
            if (!c.ok()) {
                return c.status();
            }
            StatusOr<std::string> t = emit_expr_rec(*expr.if_true(), cipher_var, cipher_cpp);
            if (!t.ok()) {
                return t.status();
            }
            StatusOr<std::string> f = emit_expr_rec(*expr.if_false(), cipher_var, cipher_cpp);
            if (!f.ok()) {
                return f.status();
            }
            if (expr.prefer_branch()) {
                // Honored divergent_branch: real conditional (may diverge on GPU twin).
                return std::string("((") + c.value() + ".value() != 0u) ? (" + t.value() + ") : (" +
                       f.value() + "))";
            }
            return std::string("Z29::select(") + c.value() + ", " + t.value() + ", " + f.value() +
                   ")";
        }
        default:
            break;
        }
        if (Z29Expr::is_binary(expr.kind())) {
            if (!expr.left() || !expr.right()) {
                return fail(DslRuleId::E032_primitive_body, "binary expr missing operands");
            }
            StatusOr<std::string> l = emit_expr_rec(*expr.left(), cipher_var, cipher_cpp);
            if (!l.ok()) {
                return l.status();
            }
            StatusOr<std::string> r = emit_expr_rec(*expr.right(), cipher_var, cipher_cpp);
            if (!r.ok()) {
                return r.status();
            }
            switch (expr.kind()) {
            case Kind::Add:
                return std::string("Z29::add(") + l.value() + ", " + r.value() + ")";
            case Kind::Sub:
                return std::string("Z29::sub(") + l.value() + ", " + r.value() + ")";
            case Kind::Mul:
                return std::string("Z29::mul(") + l.value() + ", " + r.value() + ")";
            case Kind::Div:
                return std::string("Z29::mul(") + l.value() + ", Z29::inv(" + r.value() + "))";
            case Kind::FloorDiv:
                return std::string("Z29::floor_div(") + l.value() + ", " + r.value() + ")";
            case Kind::Mod:
                return std::string("Index29{static_cast<std::uint8_t>((") + l.value() +
                       ".value() % " + r.value() + ".value())}";
            case Kind::Pow:
                return std::string("Z29::pow(") + l.value() + ", " + r.value() + ")";
            case Kind::BitAnd:
                return std::string("Z29::bit_and(") + l.value() + ", " + r.value() + ")";
            case Kind::BitOr:
                return std::string("Z29::bit_or(") + l.value() + ", " + r.value() + ")";
            case Kind::BitXor:
                return std::string("Z29::bit_xor(") + l.value() + ", " + r.value() + ")";
            case Kind::LShift:
                return std::string("Z29::lshift(") + l.value() + ", " + r.value() + ")";
            case Kind::RShift:
                return std::string("Z29::rshift(") + l.value() + ", " + r.value() + ")";
            case Kind::Eq:
                return std::string("Z29::eq(") + l.value() + ", " + r.value() + ")";
            case Kind::Ne:
                return std::string("Z29::ne(") + l.value() + ", " + r.value() + ")";
            case Kind::Lt:
                return std::string("Z29::lt(") + l.value() + ", " + r.value() + ")";
            case Kind::Le:
                return std::string("Z29::le(") + l.value() + ", " + r.value() + ")";
            case Kind::Gt:
                return std::string("Z29::gt(") + l.value() + ", " + r.value() + ")";
            case Kind::Ge:
                return std::string("Z29::ge(") + l.value() + ", " + r.value() + ")";
            case Kind::BoolAnd:
                return std::string("Z29::bool_and(") + l.value() + ", " + r.value() + ")";
            case Kind::BoolOr:
                return std::string("Z29::bool_or(") + l.value() + ", " + r.value() + ")";
            default:
                break;
            }
        }
        if (Z29Expr::is_unary(expr.kind())) {
            if (!expr.arg()) {
                return fail(DslRuleId::E032_primitive_body, "unary expr missing operand");
            }
            StatusOr<std::string> a = emit_expr_rec(*expr.arg(), cipher_var, cipher_cpp);
            if (!a.ok()) {
                return a.status();
            }
            switch (expr.kind()) {
            case Kind::Neg:
                return std::string("Z29::neg(") + a.value() + ")";
            case Kind::Inv:
                return std::string("Z29::inv(") + a.value() + ")";
            case Kind::Atbash:
                return std::string("Z29::atbash(") + a.value() + ")";
            case Kind::BitNot:
                return std::string("Z29::bit_not(") + a.value() + ")";
            case Kind::BoolNot:
                return std::string("Z29::bool_not(") + a.value() + ")";
            default:
                break;
            }
        }
        return fail(DslRuleId::E032_primitive_body, "unknown Z29Expr kind in emit");
    }

    /// Flat Call `z29_det(a,b,c,d)` or 9 entries → `Z29MatrixN::from_row_major({...}).det()`.
    [[nodiscard]] static StatusOr<std::string>
    emit_z29_det_call(const std::vector<Z29Expr::Ptr>& args, std::string_view cipher_var,
                      std::string_view cipher_cpp) {
        if (args.size() != 4 && args.size() != 9) {
            return fail(DslRuleId::E032_primitive_body,
                        "z29_det Call emit expects 4 or 9 flattened matrix entries");
        }
        std::string parts;
        for (std::size_t i = 0; i < args.size(); ++i) {
            if (!args[i]) {
                return fail(DslRuleId::E032_primitive_body, "z29_det null matrix entry");
            }
            StatusOr<std::string> e = emit_expr_rec(*args[i], cipher_var, cipher_cpp);
            if (!e.ok()) {
                return e.status();
            }
            if (i != 0) {
                parts += ", ";
            }
            parts += e.value();
        }
        if (args.size() == 4) {
            return std::string("Z29Matrix2::from_row_major(std::array<Index29, 4>{") + parts +
                   "}).det()";
        }
        return std::string("Z29Matrix3::from_row_major(std::array<Index29, 9>{") + parts +
               "}).det()";
    }

    /// Flat Call `z29_matmul` with n²+n entries → expand to `mul_vec` then take no default;
    /// emit the full `mul_vec` expression as component trees joined is not Index29.
    /// Instead: expand via MatrixIr and emit component 0..n-1 is wrong for one return.
    /// Emit path: rebuild MatrixIr and emit `mul_vec` C++ returning array, then `.at(0)` is
    /// only valid when args include a trailing component — require n²+n entries and emit
    /// the linear form for a requested component via expanding all components' trees for
    /// the last-arg-as-index convention: (matrix..., vec..., indexConst) — not used.
    ///
    /// v0: emit flattened matmul Call by expanding MatrixIr::mul_vec_exprs()[0] tree when
    /// the call has n²+n args (tests may use emit_expr on mul_vec_component trees instead).
    /// Prefer BuildIr `z29_matmul(...)[i]` which expands before emit.
    [[nodiscard]] static StatusOr<std::string>
    emit_z29_matmul_call(const std::vector<Z29Expr::Ptr>& args, std::string_view cipher_var,
                         std::string_view cipher_cpp) {
        std::size_t n = 0;
        if (args.size() == 6) {
            n = 2;
        } else if (args.size() == 12) {
            n = 3;
        } else {
            return fail(DslRuleId::E032_primitive_body,
                        "z29_matmul Call emit expects 6 (2x2) or 12 (3x3) flattened entries "
                        "(matrix then vector); prefer BuildIr z29_matmul(...)[i]");
        }
        std::vector<Z29Expr::Ptr> matrix_entries(args.begin(),
                                                 args.begin() + static_cast<std::ptrdiff_t>(n * n));
        StatusOr<MatrixIr> matrix = MatrixIr::make(matrix_entries);
        if (!matrix.ok()) {
            return matrix.status();
        }
        (void)matrix;
        std::string mparts;
        for (std::size_t i = 0; i < n * n; ++i) {
            StatusOr<std::string> e = emit_expr_rec(*args[i], cipher_var, cipher_cpp);
            if (!e.ok()) {
                return e.status();
            }
            if (i != 0) {
                mparts += ", ";
            }
            mparts += e.value();
        }
        std::string vparts;
        for (std::size_t i = 0; i < n; ++i) {
            StatusOr<std::string> e =
                emit_expr_rec(*args[n * n + i], cipher_var, cipher_cpp);
            if (!e.ok()) {
                return e.status();
            }
            if (i != 0) {
                vparts += ", ";
            }
            vparts += e.value();
        }
        if (n == 2) {
            return std::string("Z29Matrix2::from_row_major(std::array<Index29, 4>{") + mparts +
                   "}).mul_vec(" + vparts + ")[0]";
        }
        return std::string("Z29Matrix3::from_row_major(std::array<Index29, 9>{") + mparts +
               "}).mul_vec(std::array<Index29, 3>{" + vparts + "})[0]";
    }

    /// `z29_autokey_shift(stream, lag)` → `AutokeyRing::shift(input, i, lag)`.
    /// `stream` MUST be the HotLoop cipher var; `cipher_cpp` MUST end with `[i]`.
    [[nodiscard]] static StatusOr<std::string>
    emit_z29_autokey_shift_call(const std::vector<Z29Expr::Ptr>& args, std::string_view cipher_var,
                                std::string_view cipher_cpp) {
        if (args.size() != 2 || !args[0] || !args[1]) {
            return fail(DslRuleId::E032_primitive_body,
                        "z29_autokey_shift expects (stream, lag)");
        }
        if (args[0]->kind() != Z29Expr::Kind::Var || args[0]->name() != cipher_var) {
            return fail(DslRuleId::E032_primitive_body,
                        "z29_autokey_shift stream must be the HotLoop cipher var '" +
                            std::string(cipher_var) + "'");
        }
        StatusOr<std::string> base = stream_base_from_cipher_cpp(cipher_cpp);
        if (!base.ok()) {
            return base.status();
        }
        StatusOr<std::string> lag = emit_expr_rec(*args[1], cipher_var, cipher_cpp);
        if (!lag.ok()) {
            return lag.status();
        }
        return std::string("AutokeyRing::shift(") + base.value() + ", i, " + lag.value() + ")";
    }
};

#endif // DSL_EMIT_CPU_HPP
