#ifndef DSL_EMIT_CPU_HPP
#define DSL_EMIT_CPU_HPP

#include "parcae/core/status.hpp"
#include "parcae/core/status_or.hpp"
#include "parcae/dsl/dsl_diag.hpp"
#include "parcae/dsl/dsl_rule_id.hpp"
#include "parcae/dsl/param_ir.hpp"
#include "parcae/dsl/primitive_ir.hpp"
#include "parcae/dsl/theory_ir.hpp"
#include "parcae/dsl/z29_expr.hpp"

#include <cctype>
#include <sstream>
#include <string>
#include <string_view>
#include <utility>

/// Emit Transform-shaped C++ header text from DSL IR (docs/architecture/python-transpiler.md).
/// Output is a standalone class (not Force-registered in TransformId yet); shape matches
/// `apply_into` / interrupt pass-through used by hand transforms + DslIrApplicator.
class DslEmitCpu {
public:
    /// Lower one Z29Expr to a C++ expression using host `Z29` / `Index29`.
    /// `cipher_var` binds to `cipher_cpp` (default `input[i]`).
    [[nodiscard]] static StatusOr<std::string> emit_expr(
        const Z29Expr::Ptr& expr,
        std::string_view cipher_var = "x",
        std::string_view cipher_cpp = "input[i]") {
        if (!expr) {
            return fail(DslRuleId::E032_primitive_body, "cannot emit null Z29Expr");
        }
        return emit_expr_rec(*expr, cipher_var, cipher_cpp);
    }

    /// Full header: `#ifndef …` + `class <Pascal>Transform` with encrypt/decrypt kernels.
    [[nodiscard]] static StatusOr<std::string> emit_theory_header(
        const TheoryIr& theory,
        std::string_view cipher_var = "x") {
        if (theory.name().empty()) {
            return fail(DslRuleId::E032_primitive_body, "theory name must be non-empty");
        }
        if (!is_safe_ident(theory.name())) {
            return fail(
                DslRuleId::E032_primitive_body,
                "theory name '" + theory.name() +
                    "' is not a safe C++ identifier base ([a-z][a-z0-9_]*)");
        }
        if (!theory.encrypt_step() || !theory.decrypt_step()) {
            return fail(
                DslRuleId::E032_primitive_body,
                "theory '" + theory.name() + "' needs encrypt_step and decrypt_step to emit CPU");
        }
        for (const ParamIr& p : theory.params()) {
            if (!is_safe_ident(p.name())) {
                return fail(
                    DslRuleId::E040_param_domain,
                    "param '" + p.name() + "' is not a safe C++ identifier");
            }
        }

        StatusOr<std::string> enc =
            emit_expr(theory.encrypt_step(), cipher_var, "input[i]");
        if (!enc.ok()) {
            return enc.status();
        }
        StatusOr<std::string> dec =
            emit_expr(theory.decrypt_step(), cipher_var, "input[i]");
        if (!dec.ok()) {
            return dec.status();
        }

        const std::string class_name = to_pascal(theory.name()) + "Transform";
        const std::string guard = to_guard(class_name);

        std::ostringstream out;
        out << "// Generated by parcae-compile (DslEmitCpu) — do not hand-edit.\n";
        out << "// theory_id=" << theory.name() << " family=" << TheoryIr::family_str(theory.family())
            << " tier=" << TheoryIr::tier_str(theory.tier()) << "\n";
        out << "#ifndef " << guard << "\n";
        out << "#define " << guard << "\n\n";
        out << "#include \"parcae/core/index29.hpp\"\n";
        out << "#include \"parcae/core/status.hpp\"\n";
        out << "#include \"parcae/core/status_or.hpp\"\n";
        out << "#include \"parcae/core/z29.hpp\"\n";
        out << "#include \"parcae/interrupt/policy.hpp\"\n";
        out << "#include \"parcae/transform/transform_buffer.hpp\"\n";
        out << "#include \"parcae/transform/transform_direction.hpp\"\n\n";
        out << "#include <cstdint>\n";
        out << "#include <span>\n";
        out << "#include <string>\n";
        out << "#include <string_view>\n";
        out << "#include <vector>\n\n";
        out << "#include <nlohmann/json.hpp>\n\n";
        out << "/// Emitted CPU transform for theory `" << theory.name() << "`.\n";
        out << "/// Transform-shaped (`apply_into`); not yet a TransformId catalog entry.\n";
        out << "class " << class_name << " {\n";
        out << "public:\n";
        out << "    static constexpr std::string_view theory_id = \"" << theory.name() << "\";\n\n";
        out << "    " << class_name << "() = default;\n\n";

        // kernel
        out << "    [[nodiscard]] static Status kernel(\n";
        out << "        std::span<const Index29> input,\n";
        out << "        std::span<Index29> output,\n";
        for (const ParamIr& p : theory.params()) {
            out << "        Index29 " << p.name() << ",\n";
        }
        out << "        TransformDirection direction,\n";
        out << "        std::span<const std::size_t> skip_indices_sorted) {\n";
        out << "        Status sizes = parcae::transform_buf::require_same_length(input, output);\n";
        out << "        if (!sizes.ok()) {\n";
        out << "            return sizes;\n";
        out << "        }\n";
        out << "        for (std::size_t i = 0; i < input.size(); ++i) {\n";
        out << "            if (parcae::transform_buf::should_skip(skip_indices_sorted, i)) {\n";
        out << "                output[i] = input[i];\n";
        out << "                continue;\n";
        out << "            }\n";
        out << "            if (direction == TransformDirection::Encrypt) {\n";
        out << "                output[i] = " << enc.value() << ";\n";
        out << "            } else {\n";
        out << "                output[i] = " << dec.value() << ";\n";
        out << "            }\n";
        out << "        }\n";
        out << "        return Status::success();\n";
        out << "    }\n\n";

        // apply_into
        out << "    [[nodiscard]] static Status apply_into(\n";
        out << "        std::span<const Index29> input,\n";
        out << "        std::span<Index29> output,\n";
        out << "        const nlohmann::json& params,\n";
        out << "        TransformDirection direction,\n";
        out << "        const InterruptPolicy& interrupt = InterruptPolicy::none()) {\n";
        out << "        StatusOr<ParsedParams> parsed = parse_params(params);\n";
        out << "        if (!parsed.ok()) {\n";
        out << "            return parsed.status();\n";
        out << "        }\n";
        out << "        Status range = parcae::transform_buf::validate_interrupt_range(\n";
        out << "            interrupt, input.size(), \"" << theory.name() << "\");\n";
        out << "        if (!range.ok()) {\n";
        out << "            return range;\n";
        out << "        }\n";
        out << "        return kernel(\n";
        out << "            input,\n";
        out << "            output,\n";
        for (const ParamIr& p : theory.params()) {
            out << "            parsed.value()." << p.name() << ",\n";
        }
        out << "            direction,\n";
        out << "            parcae::transform_buf::skip_span(interrupt));\n";
        out << "    }\n\n";

        out << "    [[nodiscard]] static StatusOr<std::vector<Index29>> apply(\n";
        out << "        std::span<const Index29> input,\n";
        out << "        const nlohmann::json& params,\n";
        out << "        TransformDirection direction,\n";
        out << "        const InterruptPolicy& interrupt = InterruptPolicy::none()) {\n";
        out << "        std::vector<Index29> out(input.size());\n";
        out << "        Status st = apply_into(input, out, params, direction, interrupt);\n";
        out << "        if (!st.ok()) {\n";
        out << "            return st;\n";
        out << "        }\n";
        out << "        return out;\n";
        out << "    }\n\n";

        out << "private:\n";
        out << "    struct ParsedParams {\n";
        for (const ParamIr& p : theory.params()) {
            out << "        Index29 " << p.name() << "{};\n";
        }
        out << "    };\n\n";

        out << "    [[nodiscard]] static StatusOr<ParsedParams> parse_params(const nlohmann::json& params) {\n";
        out << "        if (!params.is_object()) {\n";
        out << "            return Status::error(\"" << theory.name()
            << " params must be an object\");\n";
        out << "        }\n";
        out << "        if (params.size() != " << theory.params().size() << ") {\n";
        out << "            return Status::error(\"" << theory.name()
            << " params has unexpected size\");\n";
        out << "        }\n";
        out << "        ParsedParams out;\n";
        for (const ParamIr& p : theory.params()) {
            out << "        {\n";
            out << "            if (!params.contains(\"" << p.name() << "\")) {\n";
            out << "                return Status::error(\"" << theory.name() << " params."
                << p.name() << " is required\");\n";
            out << "            }\n";
            out << "            if (!params.at(\"" << p.name() << "\").is_number_integer()) {\n";
            out << "                return Status::error(\"" << theory.name() << " params."
                << p.name() << " must be an integer\");\n";
            out << "            }\n";
            out << "            const auto raw = params.at(\"" << p.name()
                << "\").get<std::int64_t>();\n";
            out << "            if (raw < " << static_cast<int>(p.min()) << " || raw > "
                << static_cast<int>(p.max()) << ") {\n";
            out << "                return Status::error(\"" << theory.name() << " params."
                << p.name() << " out of domain\");\n";
            out << "            }\n";
            out << "            out." << p.name() << " = Index29{static_cast<std::uint8_t>(raw)};\n";
            out << "        }\n";
        }
        out << "        return out;\n";
        out << "    }\n";
        out << "};\n\n";
        out << "#endif // " << guard << "\n";
        return out.str();
    }

    /// Header with a static `eval` for a `@define_primitive` body (arity args).
    [[nodiscard]] static StatusOr<std::string> emit_primitive_header(const PrimitiveIr& primitive) {
        Status st = primitive.validate();
        if (!st.ok()) {
            return st;
        }
        if (!is_safe_ident(primitive.name())) {
            return fail(
                DslRuleId::E032_primitive_body,
                "primitive name '" + primitive.name() + "' is not a safe C++ identifier");
        }
        for (const std::string& n : primitive.param_names()) {
            if (!is_safe_ident(n)) {
                return fail(
                    DslRuleId::E032_primitive_body,
                    "primitive param '" + n + "' is not a safe C++ identifier");
            }
        }

        // For primitives, every param is a C++ Index29 argument (no cipher stream).
        StatusOr<std::string> body_cpp =
            emit_expr_rec(*primitive.body(), /*cipher_var=*/"", /*cipher_cpp=*/"");
        if (!body_cpp.ok()) {
            return body_cpp.status();
        }

        const std::string class_name = to_pascal(primitive.name()) + "Primitive";
        const std::string guard = to_guard(class_name);

        std::ostringstream out;
        out << "// Generated by parcae-compile (DslEmitCpu) — do not hand-edit.\n";
        out << "#ifndef " << guard << "\n";
        out << "#define " << guard << "\n\n";
        out << "#include \"parcae/core/index29.hpp\"\n";
        out << "#include \"parcae/core/status.hpp\"\n";
        out << "#include \"parcae/core/status_or.hpp\"\n";
        out << "#include \"parcae/core/z29.hpp\"\n\n";
        out << "#include <string_view>\n\n";
        out << "class " << class_name << " {\n";
        out << "public:\n";
        out << "    static constexpr std::string_view primitive_id = \"" << primitive.name()
            << "\";\n\n";
        out << "    [[nodiscard]] static Index29 eval(";
        for (std::size_t i = 0; i < primitive.param_names().size(); ++i) {
            if (i > 0) {
                out << ", ";
            }
            out << "Index29 " << primitive.param_names()[i];
        }
        out << ") {\n";
        out << "        return " << body_cpp.value() << ";\n";
        out << "    }\n";
        out << "};\n\n";
        out << "#endif // " << guard << "\n";
        return out.str();
    }

    [[nodiscard]] static std::string to_pascal(std::string_view snake) {
        std::string out;
        bool upper = true;
        for (char ch : snake) {
            if (ch == '_') {
                upper = true;
                continue;
            }
            if (upper) {
                out.push_back(static_cast<char>(std::toupper(static_cast<unsigned char>(ch))));
                upper = false;
            } else {
                out.push_back(ch);
            }
        }
        return out;
    }

private:
    DslEmitCpu() = delete;

    [[nodiscard]] static Status fail(std::string_view rule_id, std::string message) {
        return DslDiag::make(rule_id, std::move(message)).to_status();
    }

    [[nodiscard]] static bool is_safe_ident(std::string_view s) {
        if (s.empty()) {
            return false;
        }
        const unsigned char c0 = static_cast<unsigned char>(s[0]);
        if (!(std::islower(c0) || s[0] == '_')) {
            // allow leading underscore; theory ids recommended [a-z]…
            if (!std::isalpha(c0) && s[0] != '_') {
                return false;
            }
        }
        for (char ch : s) {
            const unsigned char c = static_cast<unsigned char>(ch);
            if (!(std::isalnum(c) || ch == '_')) {
                return false;
            }
        }
        return true;
    }

    [[nodiscard]] static std::string to_guard(std::string_view class_name) {
        std::string g;
        for (char ch : class_name) {
            const unsigned char c = static_cast<unsigned char>(ch);
            if (std::isalnum(c)) {
                g.push_back(static_cast<char>(std::toupper(c)));
            } else {
                g.push_back('_');
            }
        }
        g += "_HPP";
        return g;
    }

    [[nodiscard]] static StatusOr<std::string> emit_expr_rec(
        const Z29Expr& expr,
        std::string_view cipher_var,
        std::string_view cipher_cpp) {
        using Kind = Z29Expr::Kind;
        switch (expr.kind()) {
        case Kind::Const:
            return std::string("Index29{") + std::to_string(expr.const_value()) + "u}";
        case Kind::Var: {
            if (!cipher_var.empty() && expr.name() == cipher_var) {
                if (cipher_cpp.empty()) {
                    return fail(
                        DslRuleId::E032_primitive_body,
                        "cipher_var used but cipher_cpp is empty");
                }
                return std::string(cipher_cpp);
            }
            if (!is_safe_ident(expr.name())) {
                return fail(
                    DslRuleId::E032_primitive_body,
                    "unsafe var name '" + expr.name() + "' in emit");
            }
            return expr.name();
        }
        case Kind::Add:
        case Kind::Sub:
        case Kind::Mul:
        case Kind::Mod: {
            if (!expr.left() || !expr.right()) {
                return fail(DslRuleId::E032_primitive_body, "binary expr missing operands");
            }
            StatusOr<std::string> l = emit_expr_rec(*expr.left(), cipher_var, cipher_cpp);
            if (!l.ok()) {
                return l.status();
            }
            StatusOr<std::string> r = emit_expr_rec(*expr.right(), cipher_var, cipher_cpp);
            if (!r.ok()) {
                return r.status();
            }
            const char* op = "add";
            if (expr.kind() == Kind::Sub) {
                op = "sub";
            } else if (expr.kind() == Kind::Mul) {
                op = "mul";
            } else if (expr.kind() == Kind::Mod) {
                // No Z29::mod — emit portable remainder into Index29 domain.
                return std::string("Index29{static_cast<std::uint8_t>((") + l.value() +
                       ".value() % " + r.value() + ".value())}";
            }
            return std::string("Z29::") + op + "(" + l.value() + ", " + r.value() + ")";
        }
        case Kind::Neg:
        case Kind::Inv:
        case Kind::Atbash: {
            if (!expr.arg()) {
                return fail(DslRuleId::E032_primitive_body, "unary expr missing operand");
            }
            StatusOr<std::string> a = emit_expr_rec(*expr.arg(), cipher_var, cipher_cpp);
            if (!a.ok()) {
                return a.status();
            }
            const char* op = "neg";
            if (expr.kind() == Kind::Inv) {
                op = "inv";
            } else if (expr.kind() == Kind::Atbash) {
                op = "atbash";
            }
            return std::string("Z29::") + op + "(" + a.value() + ")";
        }
        case Kind::Call: {
            // Lower builtins to the same Z29 shape as dedicated nodes.
            const std::string& n = expr.name();
            const auto& args = expr.args();
            auto bin = [&](const char* zop) -> StatusOr<std::string> {
                if (args.size() != 2 || !args[0] || !args[1]) {
                    return fail(
                        DslRuleId::E032_primitive_body,
                        "call '" + n + "' expects 2 args for emit");
                }
                StatusOr<std::string> l = emit_expr_rec(*args[0], cipher_var, cipher_cpp);
                if (!l.ok()) {
                    return l.status();
                }
                StatusOr<std::string> r = emit_expr_rec(*args[1], cipher_var, cipher_cpp);
                if (!r.ok()) {
                    return r.status();
                }
                return std::string("Z29::") + zop + "(" + l.value() + ", " + r.value() + ")";
            };
            auto unary = [&](const char* zop) -> StatusOr<std::string> {
                if (args.size() != 1 || !args[0]) {
                    return fail(
                        DslRuleId::E032_primitive_body,
                        "call '" + n + "' expects 1 arg for emit");
                }
                StatusOr<std::string> a = emit_expr_rec(*args[0], cipher_var, cipher_cpp);
                if (!a.ok()) {
                    return a.status();
                }
                return std::string("Z29::") + zop + "(" + a.value() + ")";
            };
            if (n == "z29_add") {
                return bin("add");
            }
            if (n == "z29_sub") {
                return bin("sub");
            }
            if (n == "z29_mul") {
                return bin("mul");
            }
            if (n == "z29_inv") {
                return unary("inv");
            }
            if (n == "z29_neg") {
                return unary("neg");
            }
            if (n == "z29_atbash") {
                return unary("atbash");
            }
            if (n == "z29_mod") {
                if (args.size() != 2 || !args[0] || !args[1]) {
                    return fail(DslRuleId::E032_primitive_body, "z29_mod expects 2 args");
                }
                StatusOr<std::string> l = emit_expr_rec(*args[0], cipher_var, cipher_cpp);
                if (!l.ok()) {
                    return l.status();
                }
                StatusOr<std::string> r = emit_expr_rec(*args[1], cipher_var, cipher_cpp);
                if (!r.ok()) {
                    return r.status();
                }
                return std::string("Index29{static_cast<std::uint8_t>((") + l.value() +
                       ".value() % " + r.value() + ".value())}";
            }
            return fail(
                DslRuleId::E032_primitive_body,
                "cannot emit unknown primitive call '" + n + "'");
        }
        }
        return fail(DslRuleId::E032_primitive_body, "unknown Z29Expr kind in emit");
    }
};

#endif // DSL_EMIT_CPU_HPP
